config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  resources :products
  get 'say/hello'

  get 'say/goodbye'

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
	def self.search(search)
	 	if search
    		#find(:all, :conditions => ['customer_email LIKE ? OR customer_phone LIKE ? OR product LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%"])
    		select(:invoice).uniq.where("customer_email LIKE ? OR customer_phone LIKE ? OR product LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
  		end
  	end
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
    if params[:search]
      @invoices = Invoice.search(params[:search])
    else
      @invoices = Invoice.select(:invoice).uniq
    end
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)
    @details = params[:invoice]
    @product = params[:ProdName] #product - list
    @rate = params[:Rate]# rate - list
    @quantity = params[:Quantity]# quantity - list
    @amount = params[:Amount]# amount - list
    
    @date = params[:date]

    puts "date is " + @details["date"].to_s# year - month - date
    
    new_records = Array.new
    successFlag = 0

    for i in 0..@rate.length - 1
      new_records = {:customer_name => @details["customer_name"].to_s, :customer_phone => @details["customer_phone"], :customer_email => @details["customer_email"].to_s, :invoice =>  @details["invoice"].to_s, :invoice_date => @details["date"], :product => @product[i].to_s, :rate => @rate[i].to_f, :quantity => @quantity[i].to_i, :amount => @amount[i].to_f }
      @invoiceS = Invoice.new(new_records)
      if @invoiceS.save
        successFlag = successFlag + 1
      end# end of if-else
    end# end of for loop

    respond_to do |format|
      if successFlag >= @rate.length
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :index, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:customer_name, :customer_phone, :customer_email, :invoice, :invoice_date, :product, :rate, :quantity, :amount)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all.order("rate asc")
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :index, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :index, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:product_name, :rate)
    end
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
  	@time = Time.now
  	@files = Dir.glob('*')
  end

  def goodbye
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/invoices/_form.html.erb
<div class="row" style="margin-top:5%">
  <div class="col-lg-2"></div>
  <div class="col-lg-8">
    <div class="jumbotron col-temp" style="background-color:#606060">
      <div class="row">
        <div class="col-md-2 col-sm-2 col-btn-sidebar">
          <button type="button" class="btn btn-transparent col-md-12" onclick="location.href='/products';"> Products </button>
          <button type="button"  class="btn btn-yellow col-md-12" onclick="location.href='/invoices';"> Invoices </button>
        </div>
        <div class="col-md-10 col-sm-10">
          <div class="jumbotron col-temp" style="padding-top:40px;margin-bottom:0px;margin-left:-15px">
            <div class="row">
              <div class="col-md-1 col-sm-1"></div>
              <div class="col-md-10 col-sm-10">
                <ol class="breadcrumb">
                  <li><a href="/invoices">Invoices</a></li>
                  <li>New Invoice</li>
                </ol>
              </div>
              <div class="col-md-1 col-sm-1"></div>
            </div>
            <div class="row">
              <div class="col-md-1 col-sm-1"></div>
              <div class="col-md-10 col-sm-10">
                <%= form_for(@invoice) do |f| %>
                  <% if @invoice.errors.any? %>
                    <div id="error_explanation">
                      <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>
                      <ul>
                        <% @invoice.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                        <% end %>
                      </ul>
                    </div>
                  <% end %>
                  <div class="row">
                    <div class="col-md-6 col-sm-6">
                      <div class="field">
                        <%= f.label :customer_name %><br>
                        <%= f.text_field :customer_name, :class => "form-control" %>
                      </div>
                    </div>
                    <div class="col-md-6 col-sm-6">
                      <div class="field">
                        <% num = Invoice.last.invoice[3..5].to_i + 1 %>
                        <% invoiceNew = Invoice.last.invoice[0..2]; cnt = 3 - num.to_s.length - 1 %>
                        <% for i in 0..cnt %>
                          <% invoiceNew += "0" %>
                        <% end %>
                        <% invoiceNew += num.to_s %>
                        <%= f.label :invoice %><br>
                        <%= f.text_field :invoice, :class => "form-control", :value => invoiceNew %>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-6 col-sm-6">
                      <div class="field">
                        <%= f.label :customer_phone %><br>
                        <%= f.number_field :customer_phone, :class => "form-control" %>
                      </div>
                    </div>
                    <div class="col-md-6 col-sm-6">
                      <div class="field">
                        <%= f.label :invoice_date %><br>
                        <% #f.date_select :invoice_date, :class => "form-control" %>
                        <input type="date" name="invoice[date]" class="form-control" value=<%= Time.now %>/>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-6 col-sm-6">
                      <div class="field">
                        <%= f.label :customer_email %><br>
                        <%= f.text_field :customer_email, :class => "form-control" %>
                      </div>
                    </div>
                    <div class="col-md-6 col-sm-6"></div>
                  </div>
                  <div class="row">
                    <div class="col-md-12 col-sm-12">
                      <table class="table" id="newTable">
                        <tbody>
                          <tr><!--for new product row-->
                            <td style="width:40%">
                              <div class="field form-group">
                                <h6><strong>Product</strong></h6>
                                <% f.collection_select :product, Product.order(:product_name),:product_name,:product_name , :class => "form-control" %>
                                <input type="hidden" id="product_name" name="ProdName[]"/>
                                <select class="form-control" id="product" name="Product[]" onchange="overrideLink(this)">
                                  <option>-- Select Product --</option>
                                  <% Product.all.each do |product| %>
                                    <option value=<%= product.rate %>><%= product.product_name %></option>
                                  <% end %>
                                  <option>Custom (Fish curry rice, extra)</option>
                                </select>
                              </div>
                            </td>
                            <td style="width:10%">
                              <div class="field form-group">
                                <h6><strong>Rate</strong></h6>
                                <%= f.text_field :rate, :class => "form-control", :name => 'Rate[]' %>
                                <a href="" id="overLink" style="display:none">Override</a>
                              </div>
                            </td>
                            <td style="width:10%">
                              <div class="field form-group">
                                <h6><strong>Quantity</strong></h6>
                                <%= f.number_field :quantity, :class => "form-control", :onchange => "amount(this)", :min => 1, :value => 1, :name => 'Quantity[]' %>
                              </div>
                            </td>
                            <td style="width:15%">
                              <div class="field form-group">
                                <h6><strong>Amount</strong></h6>
                                <%= f.text_field :amount, :class => "form-control", :name => 'Amount[]' %>
                              </div>
                            </td>
                            <td style="width:20%">
                              <div class="actions" style="padding-top:35px">
                                <button type="button" class="btn" style="padding: 3px 12px; display:block;" name="Remove[]" onclick="deleteTableRow(this)">Remove</button>
                              </div>
                            </td>
                          </tr>
                          <tr><!-- for add button table row-->
                            <td style="width:40%">
                              <div class="field form-group">
                                <h6><strong>Product</strong></h6> 
                                <% f.collection_select :product, Product.order(:product_name),:product_name,:product_name , :class => "form-control" %>
                                <select class="form-control" id="product" onchange="overrideLink()" disabled>
                                  <option>-- Select Product --</option>
                                  <% Product.all.each do |product| %>
                                    <option value=<%= product.rate %>><%= product.product_name %></option>
                                  <% end %>
                                  <option>Custom</option>
                                </select>
                              </div>
                            </td>
                            <td style="width:10%"></td>
                            <td style="width:10%"></td>
                            <td style="width:15%"></td>
                            <td style="width:20%">
                              <div class="actions" style="padding-top:35px;">
                                <button type="button" class="btn" style="padding: 3px 26px" onclick="addTableRow()">Add</button>
                              </div>
                            </td>
                          </tr>
                        </tbody>
                      </table>
                      <div class="actions">
                        <button type="submit" class="btn btn-success">Create Invoice</button>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
              <div class="col-md-1 col-sm-1"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-2"></div>
</div>

app/views/invoices/destroy.html.erb
<p id="notice"><%= notice %></p>

<div class="row" style="margin-top:8%">
  <div class="col-md-2"></div>
  <div class="col-md-1 col-temp">
    <div class="jumbotron" style="background-color:#606060; height:354px">
      <button type="button" class="btn btn-transparent col-md-12" onclick="location.href='/products';"> Products </button>
      <button type="button"  class="btn btn-yellow col-md-12" onclick="location.href='/invoices';"> Invoices </button>
    </div>
  </div>
  <div class="col-md-7 col-temp">
    <div class="jumbotron">
      <div class="">
        <div class="row">
          <div class="col-md-1"></div>
          <div class="col-md-11">
            <ol class="breadcrumb">
              <li>Invoices</li>
              <li>Invoices List</li>
            </ol>
          </div>
        </div>
        <div class="row">
          <div class="col-md-1"></div>
          <div class="col-md-8">
            <form role="search">
              <div class="form-group col-md-10">
                <input type="text" class="form-control" placeholder="Search by contact details or product names">
              </div>
              <button type="submit" class="btn btn-default col-md-2">Search</button>
            </form>
          </div>
          <div class="col-md-3">
            <button type="button" class="btn btn-success" onclick="location.href='/invoices/new';"> + New Invoice </button>
          </div>
        </div>
        <div class="row">
          <div class="col-md-1"></div>
          <div class="col-md-10">
            <table class="table">
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Invoice Number</th>
                  <th>Customer</th>
                  <th>Products</th>
                  <th>Total</th>
                </tr>
              </thead>
              <tbody>
                <% @invoices.each do |invoice| %>
                  <% @subInvoice = Invoice.where("invoice =?",invoice.invoice) %>
                  <% prod = ""; name = ""; totalAmount = 0; date = ""; length = @subInvoice.all.length; i = 0 %>
                  <% @subInvoice.each do |sub| %>
                    <% i += 1 %>
                    <% if i == 1 %>
                      <% prod += sub.quantity.to_s + " x " + sub.product %>
                    <% elsif i < 3 %>
                      <% prod += ", " + sub.quantity.to_s + " x " + sub.product %>
                    <% end %> 
                    <% totalAmount += sub.amount; name = sub.customer_name; date = sub.invoice_date.strftime("%e %B %Y") %>
                  <% end %>
                  <% if i >= 3 %>
                    <% prod += " and  " + (i - 2).to_s + " more" %>
                  <% end %>
                  <tr>
                    <td width="12%"><%= date %></td>
                    <td width="10%"><%= invoice.invoice %></td>
                    <td width="17%"><%= name %></td>                    
                    <td width="53%"><%= prod %></td>
                    <td width="8%"><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <div class="col-md-1"></div>
        </div>
        <div class="row">
          <div class="col-md-8"></div>
          <div class="col-md-4" style="padding-left:5%">
            <nav>
              <ul class="pagination">
                <li><a href="#" aria-label="Previous"><span aria-hidden="true">&laquo; Prev</span></a></li>
                <li><a href="#" aria-label="Next"><span aria-hidden="true">Next &raquo;</span></a></li>
              </ul>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-2"></div>
</div>
            

app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form' %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row" style="margin-top:5%">
  <div class="col-lg-2"></div>
  <div class="col-lg-8 col-md-12">
    <div class="jumbotron col-temp" style="background-color:#606060">
      <div class="row">
        <div class="col-md-2 col-sm-12 col-btn-sidebar">
          <button type="button" class="btn btn-transparent col-md-12" onclick="location.href='/products';"> Products </button>
          <button type="button"  class="btn btn-yellow col-md-12" onclick="location.href='/invoices';"> Invoices </button>
        </div>
        <div class="col-md-10 col-sm-12">
          <div class="jumbotron col-temp" style="padding-top:40px;margin-bottom:0px;margin-left:-15px">
            <div class="row">
              <div class="col-md-1 col-sm-1"></div>
              <div class="col-md-11 col-sm-11">
                <ol class="breadcrumb">
                  <li>Invoices</li>
                  <li>Invoices List</li>
                </ol>
              </div>
            </div>
            <div class="row">
              <div class="col-md-1 col-sm-1"></div>
              <div class="col-md-8 col-sm-8">
                <%= form_tag(invoices_path, :method => "get", id: "search-form", :role => "search") do %>
                  <div class="form-group col-md-10 col-sm-9">
                    <%= text_field_tag :search, params[:search], :class => "form-control",  :placeholder => "Search by contact details or product names" %>
                  </div>
                  <%= submit_tag "Search", :name => nil, :class => "btn btn-default col-md-2" %>
                <% end %>
              </div>
              <div class="col-md-3 co-sm-3">
                <button type="button" class="btn btn-success" onclick="location.href='/invoices/new';"> + New Invoice </button>
              </div>
            </div>
            <div class="row">
              <div class="col-md-1 col-sm-1"></div>
              <div class="col-md-10 col-sm-10">
                <table class="table" id="tableInvoice">
                  <thead>
                    <tr>
                      <th>Date</th>
                      <th>Invoice Number</th>
                      <th>Customer</th>
                      <th>Products</th>
                      <th>Total</th>
                    </tr>
                  </thead>
                  <tbody><!-- display invoice & other details -->
                    <% @invoices.each do |invoice| %>
                      <% @subInvoice = Invoice.where("invoice =?",invoice.invoice) %>
                      <% prod = ""; name = ""; totalAmount = 0; date = ""; length = @subInvoice.all.length; i = 0 %>
                      <% @subInvoice.each do |sub| %>
                        <% i += 1 %>
                        <% if i == 1 %>
                          <% prod += sub.quantity.to_s + " x " + sub.product %>
                        <% elsif i < 3 %>
                          <% prod += ", " + sub.quantity.to_s + " x " + sub.product %>
                        <% end %> 
                        <% totalAmount += sub.amount; name = sub.customer_name; date = sub.invoice_date.strftime("%e %B %Y") %>
                      <% end %>
                      <% if i >= 3 %>
                        <% prod += " and  " + (i - 2).to_s + " more" %>
                      <% end %>
                      <tr>
                        <td width="12%"><%= date %></td>
                        <td width="10%"><%= invoice.invoice %></td>
                        <td width="17%"><%= name %></td>                    
                        <td width="53%"><%= prod %></td>
                        <td width="8%"><%= totalAmount.to_s %></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
              <div class="col-md-1 col-sm-1"></div>
            </div>
            <div class="row">
              <div class="col-md-8 col-sm-8"></div>
              <div class="col-md-4 col-sm-4" style="padding-left:5%">
                <nav>
                  <ul class="pagination">
                    <input type="hidden" id="start" value="0" />
                    <input type="hidden" id="end" value="5" />
                    <li><a href="#" aria-label="Previous" onclick="onPrev()"><span aria-hidden="true">&laquo; Prev</span></a></li>
                    <li><a href="#" aria-label="Next" onclick="onNext()"><span aria-hidden="true">Next &raquo;</span></a></li>
                  </ul>
                </nav>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-2"></div>
</div>

app/views/invoices/new.html.erb
<%= render 'form' %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer name:</strong>
  <%= @invoice.customer_name %>
</p>

<p>
  <strong>Customer phone:</strong>
  <%= @invoice.customer_phone %>
</p>

<p>
  <strong>Customer email:</strong>
  <%= @invoice.customer_email %>
</p>

<p>
  <strong>Invoice:</strong>
  <%= @invoice.invoice %>
</p>

<p>
  <strong>Invoice date:</strong>
  <%=  %>
</p>

<p>
  <strong>Product:</strong>
  <%= @invoice.product %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @invoice.rate %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @invoice.quantity %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @invoice.amount %>
</p>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VacLabs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'bootstrap.min', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'style', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'bootstrap.min', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'jquery-1.11.2.min', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'style', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<div class="row" style="margin-top:5%">
  <div class="col-lg-2"></div>
  <div class="col-lg-8 col-md-12">
    <div class="jumbotron col-temp" style="background-color:#606060">
      <div class="row">
        <div class="col-md-2 col-sm-12 col-btn-sidebar">
          <button type="button" class="btn btn-yellow col-md-12" onclick="location.href='/products';"> Products </button>
          <button type="button"  class="btn btn-transparent col-md-12" onclick="location.href='/invoices';"> Invoices </button>
        </div>
        <div class="col-md-10 col-sm-12">
          <div class="jumbotron col-temp" style="padding-top:40px;margin-bottom:0px;margin-left:-15px;height:300px">
            <div class="row">
              <div class="col-md-1"></div>
              <div class="col-md-11 col-sm-11">
                <ol class="breadcrumb">
                  <li><a href="/products">Products</a></li>
                  <li>Create Product</li>
                </ol>
              </div>
            </div>
            <div class="row">
              <div class="col-md-1 col-sm-1"></div>
              <div class="col-md-10">
                <%= form_for(@product) do |f| %>
                  <% if @product.errors.any? %>
                    <div id="error_explanation">
                      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
                      <ul>
                        <% @product.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                        <% end %>
                      </ul>
                    </div>
                  <% end %>
                  <div class="row">
                    <div class="field col-md-6">
                      <%= f.label :product_name %>
                      <%= f.text_field :product_name, :class => "form-control" %>
                    </div>
                  </div>
                  <div class="row">
                    <div class="field col-md-6">
                    <%= f.label :rate %><br>
                    <%= f.text_field :rate, :class => "form-control" %>
                    </div>
                  </div>
                  <div class="actions row col-md-12">
                    <button type="submit"  class="btn btn-success">Create Product</button>
                  </div>
                <% end %>
              </div>
              <div class="col-md-1"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-2"></div>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row" style="margin-top:5%">
  <div class="col-lg-2"></div>
  <div class="col-lg-8 col-md-12">
    <div class="jumbotron col-temp" style="background-color:#606060">
      <div class="row">
        <div class="col-md-2 col-sm-12 col-btn-sidebar">
          <button type="button" class="btn btn-yellow col-md-12" onclick="location.href='/products';"> Products </button>
          <button type="button"  class="btn btn-transparent col-md-12" onclick="location.href='/invoices';"> Invoices </button>
        </div>
        <div class="col-md-10 col-sm-12">
          <div class="jumbotron col-temp" style="padding-top:40px;margin-bottom:0px;margin-left:-15px">
            <div class="row">
              <div class="col-md-1 col-sm-1"></div>
              <div class="col-md-8 col-sm-8">
                <ol class="breadcrumb">
                  <li>Products</li>
                  <li>Product List</li>
                </ol>
              </div>
              <div class="col-md-3 col-sm-3">
                <button type="button" class="btn btn-success" onclick="location.href='/products/new';"> + New Product </button>
              </div>
            </div>
            <div class="row">
              <div class="col-md-1 col-sm-1"></div>
              <div class="col-md-10 col-sm-10">
                <table class="table" id="tableProduct">
                  <thead>
                    <tr>
                      <th>Product name</th>
                      <th>Rate</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @products.each do |product| %>
                      <tr>
                        <td><%= product.product_name %></td>
                        <td><%= product.rate %></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
              <div class="col-md-1 col-sm-1"></div>
            </div>
            <div class="row">
              <div class="col-md-8 col-sm-8"></div>
              <div class="col-md-4 col-sm-4" style="padding-left:5%">
                <nav>
                  <ul class="pagination">
                    <input type="hidden" id="startP" value="0" />
                    <input type="hidden" id="endP" value="5" />
                    <li><a href="#" aria-label="Previous" onclick="prevProd()"><span aria-hidden="true">&laquo; Prev</span></a></li>
                    <li><a href="#" aria-label="Next" onclick="nextProd()"><span aria-hidden="true">Next &raquo;</span></a></li>
                  </ul>
                </nav>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-2"></div>
</div>

app/views/products/new.html.erb
<%= render 'form' %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product name:</strong>
  <%= @product.product_name %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @product.rate %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/say/hello.html.erb
<h1>Hello from rails</h1>
<p> It is now <%= Time.now %> [code on html]</p>
<p> It is now <%= @time %> [code on say_controller]</p>
<h1>Say#hello</h1>
<a href="/say/goodbye">Goodbye</a>!

<p>Time to say <%= link_to "Goodbye", say_goodbye_path %>!</p>	<!--  (link_to() -> function "variable name", route/path )-->
<p>Time in one hour: <%= 1.hour.from_now.localtime %></p>
<ul><% for file in @files %>
	<li><p> file name is: <%= file %></p></li>
<% end %></ul>
<p>Find me in app/views/say/hello.html.erb</p>